<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Career_dept extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Career_dept_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'career_dept/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'career_dept/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'career_dept/index.html';
            $config['first_url'] = base_url() . 'career_dept/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Career_dept_model->total_rows($q);
        $career_dept = $this->Career_dept_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'career_dept_data' => $career_dept,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('career_dept/career_dept_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Career_dept_model->get_by_id($id);
        if ($row) {
            $data = array(
		'iddept' => $row->iddept,
		'deptname' => $row->deptname,
	    );
            $this->load->view('career_dept/career_dept_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('career_dept'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('career_dept/create_action'),
	    'iddept' => set_value('iddept'),
	    'deptname' => set_value('deptname'),
	);
        $this->load->view('career_dept/career_dept_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'deptname' => $this->input->post('deptname',TRUE),
	    );

            $this->Career_dept_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('career_dept'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Career_dept_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('career_dept/update_action'),
		'iddept' => set_value('iddept', $row->iddept),
		'deptname' => set_value('deptname', $row->deptname),
	    );
            $this->load->view('career_dept/career_dept_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('career_dept'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('iddept', TRUE));
        } else {
            $data = array(
		'deptname' => $this->input->post('deptname',TRUE),
	    );

            $this->Career_dept_model->update($this->input->post('iddept', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('career_dept'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Career_dept_model->get_by_id($id);

        if ($row) {
            $this->Career_dept_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('career_dept'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('career_dept'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('deptname', 'deptname', 'trim|required');

	$this->form_validation->set_rules('iddept', 'iddept', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Career_dept.php */
/* Location: ./application/controllers/Career_dept.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-09 06:07:48 */
/* http://harviacode.com */