<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Career_hotels_model extends CI_Model
{


    function __construct()
    {
        parent::__construct();
    }

    // get all
    public function insertData($table,$data)
    {
        $this->db->insert($table, $data);
    }  

    // get total rows
    function total_rows_hotels($q = NULL) {
        $this->db->like('idhotels', $q);
        $this->db->or_like('hotels_name', $q);
        $this->db->from('career_hotels');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data_hotels($limit, $start = 0, $q = NULL) {
        $this->db->order_by('hotels_name', 'ASC');
        $this->db->like('idhotels', $q);
        $this->db->or_like('hotels_name', $q);
        $this->db->from('career_hotels');
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // update data
    public function updateDataHotels($table, $data, $idhotels_old)
    {
        $this->db->where('idhotels', $idhotels_old);
        $this->db->update("$table", $data);

        return true;
    }

    function deleteDataHotels($idhotels)
    {
        $this->db->where('idhotels', $idhotels);
        $this->db->delete('career_hotels');
    }

}

/* End of file Career_hotels_model.php */
/* Location: ./application/models/Career_hotels_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-06 09:54:09 */
/* http://harviacode.com */