<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Career_jobtitle_model extends CI_Model
{

    

    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }

    public function insertData($table,$data)
    {
        $this->db->insert($table, $data);
    }


    // get all
    public function getDataAll($table, $order_column, $order_type){
        $this->db->order_by("$order_column", "$order_type");
        $query = $this->db->get("$table");
        $result = $query->result();
        $this->db->save_queries = false;
        return $result;
    }

    
    function total_rows_jobtitle($q = NULL) {        
        $this->db->like('d.deptname', $q);
        $this->db->or_like('j.iddept', $q); 
        $this->db->or_like('j.position_name', $q);       
        $this->db->from('career_jobtitle as j');
        $this->db->join('career_dept as d', 'j.iddept = d.iddept', 'left');
    return $this->db->count_all_results();
    }


    function get_limit_data_jobtitle($limit, $start = 0, $q = NULL) {
        $this->db->order_by('j.position_name', 'ASC');  
        $this->db->like('d.deptname', $q);
        $this->db->or_like('j.iddept', $q); 
        $this->db->or_like('j.position_name', $q);       
        $this->db->from('career_jobtitle as j');
        $this->db->join('career_dept as d', 'j.iddept = d.iddept', 'left');
        $this->db->limit($limit, $start);
    return $this->db->get()->result();
    }

    public function updateDataJobtitle($table, $data, $idjobtitle)
    {
        $this->db->where('idjobtitle', $idjobtitle);
        $this->db->update("$table", $data);

        return true;
    }
    
    function deleteDataJobtitle($idjobtitle)
    {
        $this->db->where('idjobtitle', $idjobtitle);
        $this->db->delete('career_jobtitle');
    }

}

/* End of file Career_jobtitle_model.php */
/* Location: ./application/models/Career_jobtitle_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-09 03:43:26 */
/* http://harviacode.com */