<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Career_applicant_model extends CI_Model
{

    public $table = 'career_applicant';
    public $id = 'idapplicant';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idapplicant', $q);
	$this->db->or_like('careerid', $q);
	$this->db->or_like('firstname', $q);
	$this->db->or_like('lastname', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('tinggi_badan', $q);
	$this->db->or_like('berat_badan', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('telp_rumah', $q);
	$this->db->or_like('handphone', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('kebangsaan', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('suku', $q);
	$this->db->or_like('status_keluarga', $q);
	$this->db->or_like('date_created', $q);
	$this->db->or_like('file_picture', $q);
	$this->db->or_like('file_cv', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idapplicant', $q);
	$this->db->or_like('careerid', $q);
	$this->db->or_like('firstname', $q);
	$this->db->or_like('lastname', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('tinggi_badan', $q);
	$this->db->or_like('berat_badan', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('telp_rumah', $q);
	$this->db->or_like('handphone', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('kebangsaan', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('suku', $q);
	$this->db->or_like('status_keluarga', $q);
	$this->db->or_like('date_created', $q);
	$this->db->or_like('file_picture', $q);
	$this->db->or_like('file_cv', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Career_applicant_model.php */
/* Location: ./application/models/Career_applicant_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-11 09:51:29 */
/* http://harviacode.com */