<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Career_departement_model extends CI_Model
{

    

    function __construct()
    {
        parent::__construct();
    }

    public function insertData($table,$data)
    {
        $this->db->insert($table, $data);
    }  

    // get total rows
    function total_rows_departement($q = NULL) {
        $this->db->like('deptname', $q);
        $this->db->from('career_dept');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data_departement($limit, $start = 0, $q = NULL) {
        $this->db->order_by('deptname', 'ASC');
        $this->db->like('deptname', $q);
        $this->db->from('career_dept');
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // update data
    public function updateDataDepartement($table, $data, $iddept_old)
    {
        $this->db->where('iddept', $iddept_old);
        $this->db->update("$table", $data);

        return true;
    }

    function deleteDataDepartement($iddept)
    {
        $this->db->where('iddept', $iddept);
        $this->db->delete('career_dept');
    }

}

/* End of file Career_dept_model.php */
/* Location: ./application/models/Career_dept_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-09 06:07:48 */
/* http://harviacode.com */